### ISSUE TITLE
[QUESTION] What's the main purpose of this vagrant box?

### ISSUE THREAD

**Issue by ghost** [tlayh/vagrant-typo3cms#10]
hi thomas,

i played around with your vagrant box for TYPO3 CMS some time now. thank you again for sharing! :)

i also compared your setup to this one: https://github.com/irnnr/vagrant-typo3

i wonder what the main purpose of this box is for you: is it meant to be used (1) for developing entire TYPO3 CMS projects, (2) for developing extensions or (3) only for playing around with TYPO3 CMS? do you use it for real projects in your company?

maybe you find the time to give some insights into your workflow with this vagrant box.

kind regards

roland

**Comment by tlayh** [comment]
Hi Roland,

Number 1 not, I think the setup has to be a little bit more advanced for doing real projects, because than you want to directly install your project  into the box. I think number 2 and 3 are more the usecases. Currently I don't have much to do with TYPO3, but creating a system with a fresh TYPO3 from the master is for me the main purpose for this box. Then you can do a quick look what has changed in the past and try new features or update old extensions to work with the current version.

We also use vagrant at our company, but we don't use this box here. We have another setup that directly deploys the current project on the box too.

Best regards,
Thomas

**Comment by tlayh** [comment]
Btw. I started with the Flow and Neos box in the first place, and after that worked fine I tried the same thing for the CMS.

**Comment by ghost** [comment]
Thank you for this information.

I guess your companies setup is not public, is it?

Kind regards,

Roland
